import { Monument } from "@/types";

export const monuments: Monument[] = [
  {
    id: "taj-mahal",
    name: "Taj Mahal",
    location: "Agra, Uttar Pradesh",
    coordinates: { lat: 27.1751, lng: 78.0421 },
    description:
      "A 17th-century marble mausoleum and UNESCO World Heritage site known for symmetry and craftsmanship.",
    zones: [
      {
        id: "main-gate",
        name: "Main Gate",
        coordinates: { lat: 27.173, lng: 78.0421 },
        radius: 60,
        xp: 75,
        arrivalFact: "The grand darwaza frames your first iconic Taj view.",
        directionHint: "Face east and walk through the sandstone portal.",
      },
      {
        id: "charbagh",
        name: "Charbagh Garden Axis",
        coordinates: { lat: 27.1744, lng: 78.0423 },
        radius: 55,
        xp: 100,
        arrivalFact: "The garden follows Persian charbagh geometry.",
        directionHint: "Follow the water channel toward the marble platform.",
      },
      {
        id: "river-view",
        name: "Yamuna River View",
        coordinates: { lat: 27.1762, lng: 78.0426 },
        radius: 45,
        xp: 125,
        arrivalFact: "The rear terrace opens toward the Yamuna river.",
        directionHint: "Head behind the mausoleum for the quiet river edge.",
      },
      {
        id: "mosque-side",
        name: "West Mosque Court",
        coordinates: { lat: 27.1749, lng: 78.0408 },
        radius: 50,
        xp: 80,
        arrivalFact: "The red sandstone mosque balances the main complex.",
        directionHint: "Move toward the western flank of the platform.",
      },
    ],
    hunts: [
      {
        id: "taj-hunt-1",
        riddle: "I mirror the sky but never move. Find me in the garden spine.",
        location: "Reflecting Pool",
        coordinates: { lat: 27.1741, lng: 78.0422 },
        radius: 40,
        xp: 120,
        answerIndex: 1,
        options: ["Main Dome", "Reflecting Pool", "Royal Gate", "Minaret"],
      },
      {
        id: "taj-hunt-2",
        riddle: "I stand to the west in red sandstone, balancing prayer and symmetry.",
        location: "West Mosque Court",
        coordinates: { lat: 27.1749, lng: 78.0408 },
        radius: 45,
        xp: 130,
        answerIndex: 2,
        options: ["Yamuna Bank", "Main Dome", "West Mosque Court", "Royal Garden"],
      },
    ],
  },
  {
    id: "red-fort",
    name: "Red Fort",
    location: "Delhi",
    coordinates: { lat: 28.6562, lng: 77.241 },
    description:
      "Mughal fort complex from Shah Jahan's reign, central to India's Independence Day tradition.",
    zones: [
      {
        id: "lahori-gate",
        name: "Lahori Gate",
        coordinates: { lat: 28.6568, lng: 77.2414 },
        radius: 60,
        xp: 70,
        arrivalFact: "The ceremonial gate opens into the royal fort market axis.",
        directionHint: "Approach the main gate with tricolor view lines.",
      },
      {
        id: "diwan-i-aam",
        name: "Diwan-i-Aam",
        coordinates: { lat: 28.6558, lng: 77.2408 },
        radius: 50,
        xp: 110,
        arrivalFact: "Public audience hall where emperors heard petitions.",
        directionHint: "Walk inward from the gate toward arcaded halls.",
      },
      {
        id: "rang-mahal",
        name: "Rang Mahal",
        coordinates: { lat: 28.6552, lng: 77.2405 },
        radius: 40,
        xp: 125,
        arrivalFact: "A palace wing known for painted interiors and channels.",
        directionHint: "Continue south past the audience courtyards.",
      },
      {
        id: "hayat-bakhsh",
        name: "Hayat Bakhsh Bagh",
        coordinates: { lat: 28.6549, lng: 77.2414 },
        radius: 45,
        xp: 90,
        arrivalFact: "The garden was designed as a life-giving retreat.",
        directionHint: "Move toward the northern green quadrants.",
      },
    ],
    hunts: [
      {
        id: "red-hunt-1",
        riddle: "Where emperors listened to the people, your clue waits in arches.",
        location: "Diwan-i-Aam",
        coordinates: { lat: 28.6558, lng: 77.2408 },
        radius: 35,
        xp: 140,
        answerIndex: 0,
        options: ["Diwan-i-Aam", "Lahori Gate", "Moti Masjid", "Museum Hall"],
      },
      {
        id: "red-hunt-2",
        riddle: "Pass the main ceremonial gate where the fort first greets the city.",
        location: "Lahori Gate",
        coordinates: { lat: 28.6568, lng: 77.2414 },
        radius: 40,
        xp: 125,
        answerIndex: 1,
        options: ["Diwan-i-Khas", "Lahori Gate", "Rang Mahal", "Hayat Bakhsh"],
      },
    ],
  },
  {
    id: "qutub-minar",
    name: "Qutub Minar",
    location: "Delhi",
    coordinates: { lat: 28.5245, lng: 77.1855 },
    description:
      "A soaring minaret and heritage complex with layered Delhi Sultanate architecture.",
    zones: [
      {
        id: "entry-court",
        name: "Entry Court",
        coordinates: { lat: 28.5242, lng: 77.1852 },
        radius: 50,
        xp: 60,
        arrivalFact: "You enter a palimpsest of early Sultanate structures.",
        directionHint: "Walk past ticketing into the main archaeological lawn.",
      },
      {
        id: "iron-pillar",
        name: "Iron Pillar",
        coordinates: { lat: 28.5244, lng: 77.1856 },
        radius: 35,
        xp: 110,
        arrivalFact: "The pillar is known for corrosion resistance over centuries.",
        directionHint: "Head toward the courtyard near Quwwat-ul-Islam mosque.",
      },
      {
        id: "minar-base",
        name: "Minar Base View",
        coordinates: { lat: 28.5244, lng: 77.1855 },
        radius: 40,
        xp: 120,
        arrivalFact: "Five tapering stories showcase changing design styles.",
        directionHint: "Stand at the marked viewing ring around the tower.",
      },
      {
        id: "alai-darwaza",
        name: "Alai Darwaza",
        coordinates: { lat: 28.5239, lng: 77.1854 },
        radius: 35,
        xp: 95,
        arrivalFact: "An early Indo-Islamic gateway with geometric red sandstone work.",
        directionHint: "Move south of the minar toward the domed gateway.",
      },
    ],
    hunts: [
      {
        id: "qutub-hunt-1",
        riddle: "Rust resists me, centuries test me. Find me where all visitors pause.",
        location: "Iron Pillar",
        coordinates: { lat: 28.5244, lng: 77.1856 },
        radius: 30,
        xp: 150,
        answerIndex: 2,
        options: ["Alai Minar", "Quwwat Arch", "Iron Pillar", "Minar Base"],
      },
      {
        id: "qutub-hunt-2",
        riddle: "Look up at the tower from the marked ring where five stories rise.",
        location: "Minar Base View",
        coordinates: { lat: 28.5244, lng: 77.1855 },
        radius: 35,
        xp: 135,
        answerIndex: 3,
        options: ["Entry Court", "Alai Darwaza", "Iron Pillar", "Minar Base"],
      },
    ],
  },
];

export const monumentById = (id: string) =>
  monuments.find((m) => m.id === id) ?? monuments[0];
